#!/usr/bin/env python3

LIST_COLOR_1 = "#A0D1FF"
LIST_COLOR_2 = "#E5F2FF"
LIST_HEADING_COLOR = "#81C2FF"
WINDOW_BG_COLOR = "#C1E1FF"
TAB_BG_COLOR = "#A0D1FF"
SORT_BUTTON_COLOR = "#81C2FF"
LOAD_BUTTON_COLOR = "#81C2FF"
FILTER_BUTTON_COLOR = "#81C2FF"
FILTER_BG_COLOR = "#A0D1FF"
ENTRY_INSIDE_COLOR = "white"